language: scala
scala:
  - 2.12.4

jdk:
  - oraclejdk8
env:
  matrix:
  - COMMAND=ci-all PUBLISH=true
  global:
  - secure: dF99ay8Gv+Xzq3oks4TU0aPP1GUjnH7LaHXt0pneQzcRkEal6Jz3M0r0Jthm2C4YMN6iGxdNZcatu8cGyH6dLzEh9qPp9jWGQiqYeAAjKKrlPshyJ5OO5NwIWoJvPpYfgNa4krb+LK3/4fJekb+JE32hgl2pDa+IIQ3jVpfqgokMREHUmNzilSUNvMqfKATSWqpzNPeaSQ6eyD+XcJz1mWLC/tx/sh3QCp/bxP1mTxMmjUHYK1zc0Nu2xSoML2W9B636hbPDoa+LR821ncbEXXidLmCxrQaSgRm/dC6UkvxakRY73NT09ZtzlfQmSebAe/dFYhUzu3/3Ast9GzY4VpqKKgHq44D7JbKPlsymU0vGPpR35SQhRgcCD80ykwIiHYKPOvJ7svJWwfYmGCE/609OkEP4pC3R99WCjJ3qRo1YtTc79vA+wl9P1AomS6RojqIfJnyO2yTRJhN04MueEI1SJQwHv9pId5rPXI2scWj4HVPwisZRcU8NFEJzlA39CQacmSuiFtafsQCVI/4LNDUYmJqFxqkacig/z5qgl3U4j4n3ZMQFZNKIze37lB+RIQgEhlESe3R1nODDjv8sdj2+3WJnqvjprpIcppwDFy1GYJnnovnA1ZVdkxCi3mJ9bmjCxgRQj3UV3E8tsbqfFQzZkPIsPYmJlVUxYHbxyDI=
  - secure: KnUDDqIKZQSxNIZgwE/U9a8hrRTOKdZuhbIMWU2GpjTLTm65TZ670cTrnSOPP3mrLZp3rxLOhXt9Pgop1wVcyKQxFHr8nsYUA/RZSbd6CuRDrt+9VPuQ19eeShT/WuKJ2xFza+S6esQL2YDt8cO+Io/UPF8eURIsEZ1BHohOdoifeoA+KGhSM9cwyfVP7r8NV2pMnzX67iL/BPpYehLsD+snmG5aQLibGyG6GyD1Cii601zxs/HCKkbosL5EocIac5e/ciAbYKT3KG0EQ53A4wdzE+RC3g1OSGY7ofBkA/zGOvVH6zmmT0Jl/ObtVAg0mUseBFbCEbLhnWTr9h8smeUzV1nhBr+SnV6OlVaBAv+QzAC/amSoS3Dm5e9MrVrltmTZwXHIO18itYcdKC0Iwl8c9KhermGcovVtAqj9nawI0Uq3fvxFVf54k3b9PGeIotjkdzb1fZGZHy8hWsMYLJW+H+E9hJ6qsAbYnV5M9TBgcbVQfWcnsPh+sFgGS5li3p6dm9BZuM66Y5Z1ykpn6DZHvYP3R+7bpqaLQMEy9saDejHCYfVe48HdlC2hOF5hwjFPfH7D5gpmZbSbAohsA9z+/yRHC25idPjE1k5G6R1wEzZRTRe3xQA6fEFsuExHrp91Ms4BeWE824ImGwsRg5GFcGFjK8ZCoI+EGl4auaM=
  - secure: KErOZi0+IQyW3WRorwf3+RqVz7o+t5wz/+bSUj0sXF5oAEhrRAet0dl6Bbig1y5TOKScnztyYq0RmR4uVeZZHktXLNZbeonWA4d7nC8idIoyeMbz9B8EBXYIdgA7/WoOVL+nYRlxtTMHfsajBk/pH9IR90nknAkHVp3mb3hReXTa6kZDhO8RaLXR5q/kRM+t5N7jvflr2hWJ3AwfEJRVQfKv6AIwPhPFttf92luQa4MDwiQofjED7RN0S6gYPPoxjRiz59ttOvP+JXxAeXyCV1xBYajJmM7HSQg6CPoggFlXhPnJ+A31Rk4V5EJM/9O46ApqcRJJbhGhnxdaGg2PheMCcXT0CSWxrsN6WRO/Xq+pKVWAk1X7rMKqyIqEXkHYA5isZH5Ys4mAsX5+z0aedkMrXbUHb7HD4lcmwiYJT+Bpq51ltfr1cO2hiKFdZ+7elkPvUwQsTdvZBNdbMtrMU2DTjqFNn4gTBaSp1qUXWZMGY76qVslC3O9Yp3r3v9vPGkeMA3abAhIuh0/ytYRkJcS+1+XN78i/8KO+nAiZ4AEienKsyXuN3c4xTwE9DVHW4J0NcbYmrmBY33MJq+DyYd0ffm9u4OiUsy9iFVfjP0DeIusTe8dV0jxc2lBitsEx0qMUiSAG/zu5RZfirI0jt86x5nkKZaKjJZ8RFeSGKvA=

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_script:
  - chmod +x ./project/publish.rb

script:
  - sbt ++$TRAVIS_SCALA_VERSION $COMMAND

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7d0845db-be20-49ce-aa2b-5a64edb0a850
  - ./project/publish.rb